[general]
live_config_reload = true
import = [
	"~/dotfiles/alacritty/.config/alacritty/alacritty-theme/themes/gruvbox_material_hard_dark.toml"
]

[window]
# title = "@kyliex7"
padding = { x = 3, y = 0 }
dynamic_title = true
decorations = "None"
opacity = 0.9
blur = true
startup_mode = "Windowed"

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Propo", style = "Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[scrolling]
history = 5000
multiplier = 3 # scrolling speed

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "PasteSelection" }
]

[keyboard]
bindings = [
    # Home -> Go to the beginning of the line
    { key = "Home",  mods = "None",   chars = "\u0001" }, # Sends Ctrl+A

    # End -> Go to the end of the line
    { key = "End",   mods = "None",   chars = "\u0005" }, # Sends Ctrl+E

    # Ctrl + Left -> Move back one word
    { key = "Left",  mods = "Control", chars = "\u001bb" }, # Sends Alt+B

    # Ctrl + Right -> Move forward one word
    { key = "Right", mods = "Control", chars = "\u001bf" }, # Sends Alt+F

    # Alt + Backspace -> Delete the word before the cursor
    { key = "Backspace", mods = "Alt", chars = "\u001b\u007f" }, # Sends Alt+Backspace

    # Alt + D -> Delete the word after the cursor
    { key = "D",         mods = "Alt", chars = "\u001bd" }, # Sends Alt+D

    # { Essential Terminal Functions }

    # Copy to clipboard
    { key = "C", mods = "Control|Shift", action = "Copy" },

    # Paste from clipboard
    { key = "V", mods = "Control|Shift", action = "Paste" },

    # { Font & Window Management }

    # Increase font size
    { key = "Equals",   mods = "Control", action = "IncreaseFontSize" },
    { key = "Plus",     mods = "Control", action = "IncreaseFontSize" },

    # Decrease font size
    { key = "Minus",    mods = "Control", action = "DecreaseFontSize" },

    # Reset font size
    { key = "Key0",       mods = "Control", action = "ResetFontSize" },

    # Spawn a new Alacritty window in the same directory
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },

    # { Scrollback Buffer Navigation }

    # Scroll up one page
    { key = "PageUp",   mods = "None",    action = "ScrollPageUp" },

    # Scroll down one page
    { key = "PageDown", mods = "None",    action = "ScrollPageDown" },

    # Scroll to the very top
    { key = "Home",     mods = "Shift",   action = "ScrollToTop" },

    # Scroll to the very bottom
    { key = "End",      mods = "Shift",   action = "ScrollToBottom" },

    # { (Optional) Vi Mode for Power Users }
    { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
]
